### ISSUE TITLE
TODO: 0.1.0

### ISSUE THREAD

**Issue by kotajacob** [kotajacob/pabulum#29]
- [ ] Parse mode
- [ ] Parse operations
  - [ ] Planner
  - [ ] Quick Meal
  - [ ] Storage
  - [ ] Recipes
  - [ ] Log
- [ ] Parse time options
- [ ] Parse extra options
- [ ] Reading csv files
- [ ] Writing csv files
